2022-02-05 10:19:22 info: ---------------------------------------
2022-02-05 10:19:22 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-02-05 10:19:22 info: ---------------------------------------
2022-02-05 10:19:27 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
(node:10536) UnhandledPromiseRejectionWarning: You didn't pass in a first name!
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:10536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (1 ms)
    ✕ should have all TODO comments removed (3 ms)
    ✓ `getAnonName` should not contain unneeded console.log calls (1 ms)
    ✓ should call `new Promise()`
    ✓ should take a single argument (1 ms)
    ✓ `resolve()` should be called with a one argument
    ✓ `reject()` should be called with a one argument (1 ms)
    ✕ should resolve when called with a string argument (2 ms)
    ✕ should reject with an Error object when called without an argument (1 ms)

  ● getAnonName › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● getAnonName › should resolve when called with a string argument

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Promise

    Received value has no prototype
    Received value: undefined

      77 |     const promise = getAnonName('John');
      78 |     timeoutSpy.mockRestore();
    > 79 |     expect(promise).toBeInstanceOf(Promise);
         |                     ^
      80 |     return expect(promise).resolves.toEqual('John Doe');
      81 |   });
      82 |

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:79:21)

  ● getAnonName › should resolve when called with a string argument

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      70 |
      71 |   test('should resolve when called with a string argument', async () => {
    > 72 |     expect.assertions(3);
         |            ^
      73 |     expect(exported).toBeDefined();
      74 |     const timeoutSpy = jest
      75 |       .spyOn(global, 'setTimeout')

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:72:12)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Promise

    Received value has no prototype
    Received value: undefined

      89 |     const promise = getAnonName();
      90 |     timeoutSpy.mockRestore();
    > 91 |     expect(promise).toBeInstanceOf(Promise);
         |                     ^
      92 |     return expect(promise).rejects.toBeInstanceOf(Error);
      93 |   });
      94 | });

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:91:21)

  ● getAnonName › should reject with an Error object when called without an argument

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      82 |
      83 |   test('should reject with an Error object when called without an argument', async () => {
    > 84 |     expect.assertions(3);
         |            ^
      85 |     expect(exported).toBeDefined();
      86 |     const timeoutSpy = jest
      87 |       .spyOn(global, 'setTimeout')

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:84:12)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 6 passed, 9 total
Snapshots:   0 total
Time:        1.059 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-02-05 10:19:29 error: *** ESLint Report ***

ex1-johnWho.js
  12:1  warning  Remove commented-out code  hyf/no-commented-out-code
  19:1  warning  Remove commented-out code  hyf/no-commented-out-code
  21:1  warning  Remove commented-out code  hyf/no-commented-out-code

✖ 3 problems (0 errors, 3 warnings)


2022-02-05 10:21:25 info: ---------------------------------------
2022-02-05 10:21:25 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-02-05 10:21:25 info: ---------------------------------------
2022-02-05 10:21:29 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
(node:10611) UnhandledPromiseRejectionWarning: You didn't pass in a first name!
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:10611) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (3 ms)
    ✓ `getAnonName` should not contain unneeded console.log calls (1 ms)
    ✓ should call `new Promise()`
    ✓ should take a single argument
    ✓ `resolve()` should be called with a one argument (1 ms)
    ✓ `reject()` should be called with a one argument
    ✕ should resolve when called with a string argument (1 ms)
    ✕ should reject with an Error object when called without an argument

  ● getAnonName › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● getAnonName › should resolve when called with a string argument

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Promise

    Received value has no prototype
    Received value: undefined

      77 |     const promise = getAnonName('John');
      78 |     timeoutSpy.mockRestore();
    > 79 |     expect(promise).toBeInstanceOf(Promise);
         |                     ^
      80 |     return expect(promise).resolves.toEqual('John Doe');
      81 |   });
      82 |

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:79:21)

  ● getAnonName › should resolve when called with a string argument

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      70 |
      71 |   test('should resolve when called with a string argument', async () => {
    > 72 |     expect.assertions(3);
         |            ^
      73 |     expect(exported).toBeDefined();
      74 |     const timeoutSpy = jest
      75 |       .spyOn(global, 'setTimeout')

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:72:12)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Promise

    Received value has no prototype
    Received value: undefined

      89 |     const promise = getAnonName();
      90 |     timeoutSpy.mockRestore();
    > 91 |     expect(promise).toBeInstanceOf(Promise);
         |                     ^
      92 |     return expect(promise).rejects.toBeInstanceOf(Error);
      93 |   });
      94 | });

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:91:21)

  ● getAnonName › should reject with an Error object when called without an argument

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      82 |
      83 |   test('should reject with an Error object when called without an argument', async () => {
    > 84 |     expect.assertions(3);
         |            ^
      85 |     expect(exported).toBeDefined();
      86 |     const timeoutSpy = jest
      87 |       .spyOn(global, 'setTimeout')

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:84:12)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 6 passed, 9 total
Snapshots:   0 total
Time:        0.932 s, estimated 1 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-02-05 10:31:19 info: ---------------------------------------
2022-02-05 10:31:19 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-02-05 10:31:19 info: ---------------------------------------
2022-02-05 10:31:23 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (1 ms)
    ✓ should have all TODO comments removed (1 ms)
    ✓ `getAnonName` should not contain unneeded console.log calls (1 ms)
    ✓ should call `new Promise()`
    ✓ should take a single argument
    ✓ `resolve()` should be called with a one argument
    ✓ `reject()` should be called with a one argument (1 ms)
    ✓ should resolve when called with a string argument (2 ms)
    ✕ should reject with an Error object when called without an argument (2 ms)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: "You didn't pass in a first name!"

      90 |     timeoutSpy.mockRestore();
      91 |     expect(promise).toBeInstanceOf(Promise);
    > 92 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      93 |   });
      94 | });
      95 |

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:92:36)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 8 passed, 9 total
Snapshots:   0 total
Time:        0.901 s, estimated 1 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-02-05 10:32:21 info: ---------------------------------------
2022-02-05 10:32:21 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-02-05 10:32:21 info: ---------------------------------------
2022-02-05 10:32:24 info: All unit tests passed.
2022-02-05 10:32:27 info: All steps were completed successfully
2022-02-05 11:17:34 info: -------------------------------------------------
2022-02-05 11:17:34 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2022-02-05 11:17:34 info: -------------------------------------------------
2022-02-05 11:17:38 info: All unit tests passed.
2022-02-05 11:17:41 info: All steps were completed successfully
2022-02-08 12:53:50 info: ---------------------------------------
2022-02-08 12:53:50 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-02-08 12:53:50 info: ---------------------------------------
2022-02-08 12:53:54 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollDie.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js
  rollDie
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ should call `new Promise()` (1 ms)
    ✓ `resolve()` should be called with a one argument
    ✓ `reject()` should be called with a one argument
    ✓ should resolve when the die settles successfully (2 ms)
    ✓ should reject with an Error when the die rolls off the table (1 ms)

  ● rollDie › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        1.007 s
Ran all test suites matching /ex3-rollDie.test.js/i.
2022-02-08 12:54:26 info: ---------------------------------------
2022-02-08 12:54:26 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-02-08 12:54:26 info: ---------------------------------------
2022-02-08 12:54:28 info: All unit tests passed.
2022-02-08 12:54:29 info: All steps were completed successfully
